### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by Gtwatt1**
Provided support for dark mode in the app.

### CODE REVIEW

**Review by yury — COMMENTED** [review]
@Gtwatt1 can you remove changes from xcodeproj?

**Comment by freak4pc** [comment]
@yury Reverted the xcodeproj changes if you want to review this

**Comment by freak4pc** [comment]
Thanks @Gtwatt1 !

**Comment by freak4pc** [comment]
Btw, noticed that the onboarding still doesn't have Dark Mode fixed. Any chance you want to look into it? If not I'll do it in a separate PR @Gtwatt1 

image

**Comment by Gtwatt1** [comment]
oh sure, I would look into the onboarding screen. Thanks alot.

**Comment by Gtwatt1** [comment]
@freak4pc fixed the onboarding page dark mode, please review. I however couldnt get dark image for 'navBarExperiment'.

**Pull request merged**
