### PR TITLE
Swift 4.0.2 and RxSwift 4.0.0

### PR DESCRIPTION
**Pull request by Vkt0r**
Hi guys,

First of all I really love have all the work you've done in the app !!!. In this PR I've done the following features:

- Update the code base to use Swift 4.0.2 
- Update the code base to use RxSwift 4.0.0
 - Replace the  deprecated `MapWithIndex`, `SkipWhileWithIndex` and `TakeWhileWithIndex` with the  use of `enumerated()`, and `map`.
- Replace all the uppercase `Operator` names to use the Swift recommended in lowercase.
- Fix issues with constraints regarding the new `safeAreaLayout`.
- Support for iPhone X.
- Replace the icons with the one in the App Store and added the missed 1024x1024 image.
- Fix the issue [#9](https://github.com/RxSwiftCommunity/RxMarbles/issues/9).

Please let me know if everything goes well 😅.

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @Vkt0r ! First of all, I really really want to thank you for taking all this time to fix the app. 

This is a weird case, because this PR is literally impossible to review due to its size/magnitude, as well as how long this project hasn't been maintained. 

Due to the fact this project is actually not maintained for a while and has been not updated, If this works, I feel comfortable merging with minimal review. 

Would you please mind providing a Screen Recording of your Simulator will using the app (on iPhone X or any other), and post it here so we can get a grasp for it working correctly ?

**Comment by Vkt0r** [comment]
@freak4pc You're welcome !!! Thanks for the quick answer, I was really afraid of nobody was maintaining this project anymore. Yes you're completely right about the magnitude of the PR is huge most of all regarding the Pods update, for some some reason there aren't not in the `.gitignore` file. 

Also regarding a lot of changes regarding RxSwift 4.0.0.  Below you can find the screen recording from my iPhone X running the PR. 

[ScreenRecording_12-12-2017 13-54-22.MP4.zip](https://github.com/RxSwiftCommunity/RxMarbles/files/1552913/ScreenRecording_12-12-2017.13-54-22.MP4.zip)

@freak4pc I think one of the main points of the PR too is to be able to update the current version in the App Store, any thoughts here about how we can contact the originals owners to submit the new version  🤔??

**Comment by freak4pc** [comment]
> any thoughts here about how we can contact the originals owners to submit the new version

The app store version was uploaded by @yury IMO since it's under the AnjLab company account. 
Hey Yury! Would you still be able to upload a new version of this if you have the time - after this is merged?

**Comment by Vkt0r** [comment]
@freak4pc Thanks for the information and the time I really appreciate it !!! Did you guys have any Danger rule running or anything for the firsts contribution in the organization to be able to enter inside the organization?? I would like to form part of the organization if is possible of course 😅.

**Comment by freak4pc** [comment]
Hey @Vkt0r, once this is merged you'll be automatically invited to the organization :) 

I feel relatively comfortable merging this is in, due to the very non-maintained state of this repo, and the fact the video you posted looks good. 

Would feel much safer to get some feedback from @RxSwiftCommunity/contributors if possible

**Comment by yury** [comment]
:wave: 

Thanks for PR. I will try to release it tomorrow.

**Comment by Vkt0r** [comment]
@freak4pc No problem at all I understand perfectly, in fact one of the things I want to do in this repository when I have the time is add some (unit test + UI test + snapshot test) to have a consistent trust in any changes made for anyone in the future. At least to keep this repository alive !!! 😂. 

Thanks for the information about the invitation to the organization 👍.

**Comment by freak4pc** [comment]
@Vkt0r I went ahead and merged, if we have any issue we can always revert.
Welcome to RxSwiftCommunity :)

**Comment by Vkt0r** [comment]
@freak4pc Sure!! Thank you so much !!!!

**Comment by yury** [comment]
screen shot 2017-12-13 at 11 03 18 am

**Comment by freak4pc** [comment]
Amazing! Thanks @yury and @Vkt0r !

**Comment by yury** [comment]
Many many thanks to @freak4pc, @Vkt0r and @lauraartiles

 I wrote the following app release notes:
```
Swift 4.0.2 and RxSwift 4.0.0, iPhone X support and fixes.

Many thanks to: 
- Victor Sigler (@Vkt0r)
- Laura Artiles (@lauraartiles)
- Shai Mishali (@freak4pc)
```

If I forget anybody - please ping me.

**Comment by Vkt0r** [comment]
@freak4pc Sorry for the trouble 😅, should I receive an email automatically after the merge of the PR for the organization ?? I haven't yet 😢

**Comment by freak4pc** [comment]
Uhm yup, you are supposed to be automatically invited to the Organization. 
I don't have knowledge of the script that does that. @ashfurrow do you know if there's any extra steps to do here, or should I just invite manually?

**Comment by Vkt0r** [comment]
@freak4pc I guess for some reason the script is not running for the organization so far !! Can you please add me manually in the meantime 😅 ?. Thanks

**Comment by ashfurrow** [comment]
Mmmm sorry about that. It actually relies on per-repo web hooks – I'll set up this repo with Aeryn now.

**Comment by ashfurrow** [comment]
Should work from now on. _Really_ gotta move to Peril...

**Comment by Vkt0r** [comment]
@ashfurrow Thanks man!!, what a coincidence just listening a Podcast now in which you're invited 😂.

**Comment by Vkt0r** [comment]
@freak4pc @ashfurrow Guys I think the script is going to work for the next contributor when the PR is merged 😅. Can some of you add me to the organization, please? Thanks in advance

**Comment by ashfurrow** [comment]
Done!

**Comment by Vkt0r** [comment]
@ashfurrow Thank you 👍!!!

**Pull request merged**
